---
- name: Create music directory
  become: yes
  file:
    owner: barry
    path: /data/music/
    state: directory

# - name: Download music
#   synchronize:
#     mode: pull
#     delete: yes
#     src: /data/music/
#     dest: roles/music/files/

- name: Upload music
  synchronize:
    src: .
    dest: /data/music/
