---
- name: Create config directory
  become: yes
  file:
    path: /opt/docker/data/influxdb
    state: directory

- name: Tear down existing service
  docker_compose:
    project_name: influxdb
    state: absent
    definition:
        version: "3"
        services:
            influxdb:
                image: ""

- name: Start service
  docker_compose:
    project_name: influxdb
    remove_orphans: yes
    state: present
    definition:
      version: '3'
      services:
        influxdb:
          container_name: influxdb
          image: influxdb
          restart: unless-stopped
          environment:
            TZ: Europe/London
          ports:
              - 8086:8086
          volumes:
            - /opt/docker/data/influxdb:/var/lib/influxdb
