---
- name: Create Temporary homeconnect directory
  delegate_to: 127.0.0.1
  tempfile:
    state: directory
    suffix: homeconnect
  register: tempdir

- name: Pull Home Connect Custom Component
  delegate_to: 127.0.0.1
  git:
    repo: 'https://github.com/DavidMStraub/homeassistant-homeconnect'
    dest: "{{ tempdir.path }}"

- name: Copy latest custom component to home-assistant role
  delegate_to: 127.0.0.1
  copy:
    src: "{{ tempdir.path }}/custom_components/homeconnect"
    dest: ./roles/home-assistant/files/custom_components

- name: Cleanup
  file:
    path: "{{ tempdir.path }}"
    state: absent
  when: tempdir.path is defined
