---
- name: Install Docker CE
  become: yes
  zypper:
    name: docker
    state: present
    update_cache: yes

- name: Install Docker Compose
  become: yes
  zypper:
    name: docker-compose
    state: present
    update_cache: yes

- name: Add user to docker group
  become: yes
  user:
    name: barry
    append: yes
    groups: docker

- name: Start docker service
  become: yes
  service:
    name: docker
    enabled: yes
    state: started