- name: Update Homebrew
  homebrew:
    update_homebrew: yes
- name: Install Ansible
  homebrew:
    name: ansible
    state: latest
- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code
    state: latest
- name: Install Git
  homebrew:
    name: git
    state: latest
- name: Install Firefox
  homebrew_cask:
    name: firefox
    state: latest
- name: Install Slack
  homebrew_cask:
    name: slack
    state: latest
- name: Install Roon
  homebrew_cask:
    name: roon
    state: latest
- name: Install WhatsApp
  homebrew_cask:
    name: whatsapp
    state: latest
- name: Install Mp3tag
  homebrew_cask:
    name: mp3tag
    state: latest
- name: Install AWS CLI
  homebrew:
    name: awscli
    state: latest
- name: Install Evernote
  homebrew_cask:
    name: evernote
    state: latest
- name: Install Homebank
  homebrew:
    name: Homebank
    state: latest
- name: Install python3
  homebrew:
    name: python
    state: latest
- name: Install zoom
  homebrew_cask:
    name: zoom
    state: latest
- name: Install Calibre
  homebrew_cask:
    name: calibre
    state: latest
- name: Install VLC
  homebrew_cask:
    name: vlc
    state: latest