---
- name: Create config directory
  become: yes
  file:
    path: /opt/docker/data/nzbhydra
    state: directory

# - name: Upload configuration
#   become: yes
#   copy:
#     src: ???
#     dest: /opt/docker/data/nzbhydra

- name: Tear down existing service
  docker_compose:
    project_name: nzbhydra
    state: absent
    definition:
        version: "3"
        services:
            nzbhydra:
                image: ""

- name: Start service
  docker_compose:
    project_name: nzbhydra
    remove_orphans: yes
    state: present
    definition:
      version: '3'
      services:
        nzbhydra:
          container_name: nzbhydra
          image: linuxserver/nzbhydra2
          restart: unless-stopped
          environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
          ports:
            - 5076:5076
          volumes:
            - /opt/docker/data/nzbhydra:/config
            - /data/nzb:/downloads
