---
# - name: Create home assistant temp directory
#   tempfile:
#     state: directory
#     suffix: .homeassistant
#   register: buildcontext

# - name: Upload Dockerfile
#   copy:
#     src: Dockerfile
#     dest: "{{ buildcontext.path }}"

# - name: Upload Intermediate CA
#   copy:
#     src: opnsense-intermediate-ca.crt
#     dest: "{{ buildcontext.path }}"

# - name: Upload Root CA
#   copy:
#     src: opnsense-root-ca.crt
#     dest: "{{ buildcontext.path }}"

- name: Create data directory
  become: yes
  file:
    path: /opt/docker/data/home-assistant/config
    state: directory

- name: Upload configuration
  become: yes
  template:
    src: configuration.yaml
    dest: /opt/docker/data/home-assistant/config/configuration.yaml

- name: Upload groups
  become: yes
  copy:
    src: groups.yaml
    dest: /opt/docker/data/home-assistant/config/groups.yaml

- name: Upload automations
  become: yes
  copy:
    src: automations.yaml
    dest: /opt/docker/data/home-assistant/config/automations.yaml

- name: Upload scripts
  become: yes
  copy:
    src: scripts.yaml
    dest: /opt/docker/data/home-assistant/config/scripts.yaml

- name: Upload scenes
  become: yes
  copy:
    src: scenes.yaml
    dest: /opt/docker/data/home-assistant/config/scenes.yaml

- name: Clean custom components
  become: yes
  file:
    state: absent
    path: /opt/docker/data/home-assistant/config/custom_components

- name: Upload custom components
  become: yes
  copy:
    src: custom_components/
    dest: /opt/docker/data/home-assistant/config/custom_components

- name: Tear down existing service
  docker_compose:
    project_name: home-assistant
    state: absent
    definition:
        version: "3"
        services:
            home-assistant:
                image: ""

- name: Remove existing docker image
  docker_image:
    name: home-assistant_home-assistant
    state: absent

# - name: Add firewall rule to open port
#   become: yes
#   firewalld:
#     port: 8123/tcp
#     permanent: yes
#     immediate: yes
#     state: enabled

# - name: Add firewall rule to open ports above 1025 to permit TCP SSDP
#   become: yes
#   firewalld:
#     port: 1025-65535/tcp
#     permanent: yes
#     immediate: yes
#     state: enabled

# - name: Add firewall rule to open ports above 1025 to permit UDP SSDP
#   become: yes
#   firewalld:
#     port: 1025-65535/udp
#     permanent: yes
#     immediate: yes
#     state: enabled

- name: Start service
  docker_compose:
    project_name: home-assistant
    remove_orphans: yes
    state: present
    definition:
        version: "3"
        services:
            home-assistant:
                container_name: home-assistant
                image: homeassistant/home-assistant:0.118.4
                volumes:
                  - /opt/docker/data/home-assistant/config:/config
                  - /etc/localtime:/etc/localtime:ro
                environment:
                  - TZ=Europe/London
                  - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
                network_mode: host
                restart: unless-stopped

# - name: Cleanup
#   file:
#     path: "{{ buildcontext.path }}"
#     state: absent
#   when: buildcontext.path is defined