---
- name: Install Prequisite Packages
  become: yes
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker-ce

- name: Install Docker CE
  become: yes
  apt:
    name: docker-ce

- name: Install Docker Compose
  become: yes
  pip:
    name: docker-compose

- name: Add ubuntu user to docker group
  become: yes
  user:
    name: ubuntu
    append: yes
    groups: docker
