---
- name: Create samba temporary build directory
  tempfile:
    state: directory
    suffix: .samba
  register: buildcontext

- name: Upload Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ buildcontext.path }}"

- name: Upload smb.conf
  copy:
    src: smb.conf
    dest: "{{ buildcontext.path }}"

- name: Upload supervisord.conf
  copy:
    src: supervisord.conf
    dest: "{{ buildcontext.path }}"

- name: Add firewall rule for NETBIOS
  become: yes
  firewalld:
    port: 137-139/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Start samba
  docker_compose:
    project_name: samba
    remove_orphans: yes
    state: present
    definition:
      version: "3.7"

      services:
        samba:
          restart: unless-stopped
          build: "{{ buildcontext.path }}"
          container_name: samba
          volumes:
            - type: bind
              source: /data/music/
              target: /shared
          network_mode: host

- name: Cleanup
  file:
    path: "{{ buildcontext.path }}"
    state: absent
  when: buildcontext.path is defined
