- alias: Dark Outside
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.front_garden_motion_light_level
    below: 200
  condition:
    condition: time
    before: "21:00:00"
    after: "08:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Garden
        scene_name: Dimmed
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Colourful Evening
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Evening
    - service: hue.hue_activate_scene
      data:
        group_name: "Living room"
        scene_name: "Living Room Evening"

- alias: Dull Outside
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.front_garden_motion_light_level
    above: 200
    below: 800
  condition:
    condition: time
    before: "21:00:00"
    after: "08:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Daytime Presence
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Daytime Presence
    - service: hue.hue_activate_scene
      data:
        group_name: "Living room"
        scene_name: "Dull Outside"
    - service: light.turn_off
      data:
        entity_id:
          - group.garden

- alias: Bright Outside
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.front_garden_motion_light_level
    above: 800
    below: 3000
  condition:
    condition: time
    before: "21:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Daytime Presence
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Daytime Presence
    - service: light.turn_off
      data:
        entity_id:
          - group.garden
          - group.living_room
          - group.ethans_room
          - group.marcuss_room
          - group.bedroom
          - group.guest_room
          - group.snug

- alias: Very Bright Outside
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.front_garden_motion_light_level
    above: 3000
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Bright Outside
    - service: light.turn_off
      data:
        entity_id:
          - group.downstairs_hallway
          - group.garden
          - group.living_room
          - group.ethans_room
          - group.marcuss_room
          - group.bedroom
          - group.guest_room
          - group.snug

- alias: Wakeup
  initial_state: true
  trigger:
    platform: time
    at: "06:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Morning Variation
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Morning
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Morning
    - service: light.turn_off
      data:
        entity_id:
          - group.ethans_room
          - group.marcuss_room
    - service: media_player.media_pause
      data:
        entity_id:
          - media_player.ethan_s_room
          - media_player.marcus_room

- alias: Kids Bedtime
  initial_state: true
  trigger:
    platform: time
    at: "21:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Night

- alias: Late Night
  initial_state: true
  trigger:
    platform: time
    at: "22:30:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Late Night

- alias: Lights Out
  initial_state: true
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Night
    - service: light.turn_off
      data:
        entity_id:
          - light.living_room
          - light.bedroom

- alias: Start Kitchen Light Timer
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_motion
      from: "off"
      to: "on"
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light
    - service: timer.start
      entity_id: timer.kitchen_light

- alias: Kitchen Worktop Lights On
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.kitchen_light
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.worktop_lights

- alias: Kitchen Worktop Lights Off
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_light
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.worktop_lights

- alias: Brighten the Garden
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.front_garden_motion_motion
    to: "on"
  condition:
    - condition: numeric_state
      entity_id: sensor.front_garden_motion_light_level
      below: 50
    - condition: state
      entity_id: input_boolean.garden_scene_saved # prevents overwriting the before scene with the bright scene on motion repeat
      state: "off"
  action:
    - service: scene.create
      data:
        scene_id: garden_before
        snapshot_entities:
          - light.garden
    - service: hue.hue_activate_scene
      data:
        group_name: Garden
        scene_name: Bright
    - service: input_boolean.turn_on # to prevent overwriting the before scene with the bright scene on motion repeat
      entity_id: input_boolean.garden_scene_saved

- alias: Restore garden lights
  initial_state: true
  condition:
    - condition: numeric_state
      entity_id: sensor.front_garden_motion_light_level
      below: 50
  trigger:
    platform: state
    entity_id: binary_sensor.front_garden_motion_motion
    to: "off"
    for:
      minutes: 2
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.garden_before
    - service: input_boolean.turn_off # allow saving of the before scene again.
      entity_id: input_boolean.garden_scene_saved

- alias: Bathroom Light Left On
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.bathroom_2
      to: "on"
      for:
        minutes: 30
  action:
    - service: notify.mobile_app_barrys_iphone
      data:
        message: "Bathroom Light Left On"

- alias: Ensuite Light Left On
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.ensuite_2
      to: "on"
      for:
        minutes: 30
  action:
    - service: notify.mobile_app_barrys_iphone
      data:
        message: "Ensuite Light Left On"

- alias: Downstairs Toilet Light Left On
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.downstairs_toilet_2
      to: "on"
      for:
        minutes: 30
  action:
    - service: notify.mobile_app_barrys_iphone
      data:
        message: "Downstairs Toilet Light Left On"

- alias: Turn Power Amp On
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.hifi
      to: "playing"
      for:
        seconds: 2
    - platform: state
      entity_id: media_player.hifi
      to: "idle"
      for:
        seconds: 2
    - platform: state
      entity_id: media_player.hifi
      to: "paused"
      for:
        seconds: 2
  action:
    - service: switch.turn_on
      entity_id: switch.power_amplifier

- alias: Turn Power Amp Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.hifi
      to: "off"
      for:
        seconds: 5
  action:
    - service: switch.turn_off
      entity_id: switch.power_amplifier

- alias: Listening to Music
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('media_player.hifi', 'source', 'Playlist') }}"
      for:
        seconds: 2
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Snug
        scene_name: Chill

- alias: Listening to Records
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('media_player.hifi', 'source', 'LP12') }}"
      for:
        seconds: 2
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Snug
        scene_name: LP12

- alias: Watching the Big Screen
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.epson_projector
      to: "on"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Snug
        scene_name: Movie

- alias: Upstairs Hall Cupboard Door Open
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_hall_cupboard_door
      to: "on"
  action:
    - service: scene.create
      data:
        scene_id: upstairs_spot_2_before
        snapshot_entities:
          - light.upstairs_spot_2
    - service: light.turn_on
      data:
        entity_id: light.upstairs_spot_2
        color_temp: 153
        brightness: 254

- alias: Upstairs Hall Cupboard Door Closed
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_hall_cupboard_door
      to: "off"
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.upstairs_spot_2_before
