- name: Kitchen Away
  entities:
    light.worktop_lights: off
    light.dining_table: off
- name: Kitchen Night
  entities:
    light.worktop_lights: off
    light.dining_table: off
- name: Kitchen Late Night
  entities:
    light.worktop_lights: off
    light.dining_table: off
- name: Kitchen Early Night
  entities:
    light.worktop_lights: off
    light.dining_table:
      state: on
      brightness: 76
- name: Kitchen Late Evening
  entities:
    light.worktop_lights: on
    light.dining_table:
      state: on
      brightness: 76
- name: Kitchen Evening
  entities:
    light.worktop_lights: on
    light.dining_table:
      state: on
      brightness: 120
- name: Kitchen Daytime
  entities:
    light.worktop_lights: on
    light.dining_table:
      state: on
      brightness: 254
- name: Kitchen Morning
  entities:
    light.worktop_lights: on
    light.dining_table:
      state: on
      brightness: 254
- name: Snug Movie
  entities:
    light.snug_main: off
    switch.bookcase_light: off
    switch.lava_lamp: off
- name: Snug Music
  entities:
    light.snug_main: off
    switch.bookcase_light: off
    switch.lava_lamp: on
- name: Snug LP12
  entities:
    light.snug_main: off
    switch.bookcase_light: off
    switch.lava_lamp: on
- name: Snug On
  entities:
    light.snug_main: on
    switch.bookcase_light: on
    switch.lava_lamp: off
- name: Front Garden Off
  entities:
    light.outside_light: off
- name: Front Garden Dimmed
  entities:
    light.outside_light:
      state: on
      brightness: 24
      xy_color: [0.254, 0.097]
- name: Front Garden Bright
  entities:
    light.outside_light:
      state: on
      brightness: 255
      color_temp: 153
- name: Back Garden Off
  entities:
    light.terrace_light: off
    light.hue_outdoor_pedestal_1: off
    light.hue_outdoor_pedestal_2: off
    light.hue_outdoor_pedestal_3: off
    light.hue_outdoor_pedestal_4: off
    light.hue_outdoor_spot_1: off
    light.hue_outdoor_spot_2: off
    light.hue_outdoor_spot_3: off
    light.hue_outdoor_spot_4: off
    light.hue_outdoor_spot_5: off
- name: Back Garden Dimmed
  entities:
    light.terrace_light: off
    light.hue_outdoor_pedestal_1:
      state: on
      brightness: 20
      xy_color: [0.526, 0.411]
    light.hue_outdoor_pedestal_2:
      state: off
    light.hue_outdoor_pedestal_3:
      state: on
      brightness: 20
      xy_color: [0.526, 0.411]
    light.hue_outdoor_pedestal_4:
      state: on
      brightness: 20
      xy_color: [0.526, 0.411]
    light.hue_outdoor_spot_1:
      state: off
    light.hue_outdoor_spot_2:
      state: off
    light.hue_outdoor_spot_3:
      state: off
    light.hue_outdoor_spot_4:
      state: off
    light.hue_outdoor_spot_5:
      state: off
- name: Back Garden Bright
  entities:
    light.terrace_light:
      state: on
      brightness: 224
      xy_color: [0.26, 0.1]
    light.hue_outdoor_pedestal_1:
      state: on
      brightness: 255
      xy_color: [0.435, 0.201]
    light.hue_outdoor_pedestal_2:
      state: on
      brightness: 255
      xy_color: [0.499, 0.415]
    light.hue_outdoor_pedestal_3:
      state: on
      brightness: 255
      xy_color: [0.435, 0.201]
    light.hue_outdoor_pedestal_4:
      state: on
      brightness: 255
      xy_color: [0.435, 0.201]
    light.hue_outdoor_spot_1:
      state: off
      brightness: 224
      xy_color: [0.179, 0.413]
    light.hue_outdoor_spot_2:
      state: off
      brightness: 255
      xy_color: [0.157, 0.099]
    light.hue_outdoor_spot_3:
      state: off
      brightness: 224
      xy_color: [0.158, 0.19]
    light.hue_outdoor_spot_4:
      state: off
      brightness: 224
      xy_color: [0.521, 0.436]
    light.hue_outdoor_spot_5:
      state: off
      brightness: 224
      xy_color: [0.479, 0.328]
- name: Upstairs Hallway Morning
  entities:
    light.upstairs_spot_1:
      state: on
      brightness: 29
      color_temp: 379
    light.upstairs_spot_2:
      state: on
      brightness: 29
      color_temp: 379
    light.upstairs_spot_3:
      state: on
      brightness: 29
      color_temp: 379
- name: Upstairs Hallway Daytime
  entities:
    light.upstairs_spot_1:
      state: on
      brightness: 63
      color_temp: 309
    light.upstairs_spot_2:
      state: on
      brightness: 76
      color_temp: 239
    light.upstairs_spot_3:
      state: on
      brightness: 109
      color_temp: 156
- name: Upstairs Hallway Evening
  entities:
    light.upstairs_spot_1:
      state: on
      brightness: 55
      color_temp: 454
    light.upstairs_spot_2:
      state: on
      brightness: 55
      color_temp: 393
    light.upstairs_spot_3:
      state: on
      brightness: 55
      color_temp: 294
- name: Upstairs Hallway Night
  entities:
    light.upstairs_spot_1:
      state: on
      brightness: 21
      color_temp: 454
    light.upstairs_spot_2:
      state: off
    light.upstairs_spot_3:
      state: on
      brightness: 17
      color_temp: 454
- name: Upstairs Hallway Off
  entities:
    light.upstairs_spot_1:
      state: off
    light.upstairs_spot_2:
      state: off
    light.upstairs_spot_3:
      state: off
- name: Upstairs Cupboard Open
  entities:
    light.upstairs_spot_2:
      state: on
      color_temp: 153
      brightness: 254