- name: Kitchen Away
  entities:
    light.worktop_lights: off
    light.dining_table: off
    light.kitchen_main:
      state: on
      xy_color: [ 0.447, 0.408 ]
      brightness: 63
    light.kitchen_under_cupboards:
      state: on
      xy_color: [ 0.447, 0.408 ]
      brightness: 63
    light.kitchen_under_tall_cupboards:
      state: on
      xy_color: [ 0.447, 0.408 ]
      brightness: 63
- name: Kitchen Night
  entities:
    light.worktop_lights: off
    light.dining_table: off
    light.kitchen_main: off
    light.kitchen_under_cupboards:
      state: on
      xy_color: [ 0.547, 0.353 ]
      brightness: 44
    light.kitchen_under_tall_cupboards:
      state: on
      xy_color: [ 0.547, 0.353 ]
      brightness: 44
- name: Kitchen Late Night
  entities:
    light.worktop_lights: off
    light.dining_table: off
    light.kitchen_main:
      state: on
      xy_color: [ 0.653, 0.306 ]
      brightness: 37
    light.kitchen_under_cupboards:
      state: on
      xy_color: [ 0.523, 0.411 ]
      brightness: 37
    light.kitchen_under_tall_cupboards:
      state: on
      xy_color: [ 0.523, 0.411 ]
      brightness: 37
- name: Kitchen Early Night
  entities:
    light.worktop_lights: on
    light.dining_table:
      state: on
      brightness: 76
    light.kitchen_main:
      state: on
      xy_color: [ 0.653, 0.306 ]
      brightness: 37
    light.kitchen_under_cupboards:
      state: on
      xy_color: [ 0.523, 0.411 ]
      brightness: 37
    light.kitchen_under_tall_cupboards:
      state: on
      xy_color: [ 0.523, 0.411 ]
      brightness: 37
- name: Kitchen Evening
  entities:
    light.worktop_lights: on
    light.dining_table:
      state: on
      brightness: 120
    light.kitchen_main:
      state: on
      xy_color: [ 0.301, 0.145 ]
      brightness: 25
    light.kitchen_under_cupboards:
      state: on
      xy_color: [ 0.299, 0.144 ]
      brightness: 71
    light.kitchen_under_tall_cupboards:
      state: on
      xy_color: [ 0.299, 0.144 ]
      brightness: 71
- name: Kitchen Daytime
  entities:
    light.worktop_lights: on
    light.dining_table:
      state: on
      brightness: 254
    light.kitchen_main:
      state: on
      xy_color: [ 0.158, 0.094 ]
      brightness: 119
    light.kitchen_under_cupboards:
      state: on
      xy_color: [ 0.314, 0.331 ]
      brightness: 60
    light.kitchen_under_tall_cupboards:
      state: on
      xy_color: [ 0.314, 0.331 ]
      brightness: 60
- name: Kitchen Morning
  entities:
    light.worktop_lights: on
    light.dining_table:
      state: on
      brightness: 254
    light.kitchen_main:
      state: on
      xy_color: [ 0.526, 0.411 ]
      brightness: 114
    light.kitchen_under_cupboards:
      state: on
      xy_color: [ 0.526, 0.411 ]
      brightness: 114
    light.kitchen_under_tall_cupboards:
      state: on
      xy_color: [ 0.526, 0.411 ]
      brightness: 114
- name: Snug Off
  entities:
    light.steampunk_lamp: off
    light.tripod_lamp: off
    light.egg_lamp: off
    light.snug_main: off
    switch.bookcase_light: off
    switch.lava_lamp: off
- name: Snug Movie
  entities:
    light.steampunk_lamp: off
    light.tripod_lamp: off
    light.egg_lamp: off
    light.snug_main: off
    switch.bookcase_light: off
    switch.lava_lamp: off
- name: Snug Music
  entities:
    light.steampunk_lamp: off
    light.tripod_lamp:
      state: on
      brightness: 69
      xy_color:
        - 0.586
        - 0.357
    light.egg_lamp:
      state: on
      brightness: 186
      xy_color:
        - 0.634
        - 0.283
    light.snug_main: off
    switch.bookcase_light: off
    switch.lava_lamp: on
- name: Snug LP12
  entities:
    light.steampunk_lamp:
      state: on
      brightness: 1
      xy_color:
        - 0.526
        - 0.411
    light.tripod_lamp:
      state: on
      brightness: 25
      xy_color:
        - 0.558
        - 0.313
    light.egg_lamp:
      state: on
      brightness: 210
      xy_color:
        - 0.195
        - 0.68
    light.snug_main: off
    switch.bookcase_light: off
    switch.lava_lamp: on
- name: Snug On
  entities:
    light.steampunk_lamp:
      state: on
      brightness: 19
      xy_color:
        - 0.608
        - 0.369
    light.tripod_lamp:
      state: on
      brightness: 1
      xy_color:
        - 0.581
        - 0.389
    light.egg_lamp: off
    light.snug_main: on
    switch.bookcase_light: on
    switch.lava_lamp: off
- name: Front Garden Off
  entities:
    light.outside_light: off
- name: Front Garden Dimmed
  entities:
    light.outside_light:
      state: on
      brightness: 24
      xy_color: [0.254, 0.097]
- name: Front Garden Bright
  entities:
    light.outside_light:
      state: on
      brightness: 255
      color_temp: 153
- name: Back Garden Off
  entities:
    light.terrace_light: off
    light.hue_outdoor_pedestal_1: off
    light.hue_outdoor_pedestal_2: off
    light.hue_outdoor_pedestal_3: off
    light.hue_outdoor_pedestal_4: off
    light.hue_outdoor_spot_1: off
    light.hue_outdoor_spot_2: off
    light.hue_outdoor_spot_3: off
    light.hue_outdoor_spot_4: off
    light.hue_outdoor_spot_5: off
- name: Back Garden Dimmed
  entities:
    light.terrace_light: off
    light.hue_outdoor_pedestal_1:
      state: on
      brightness: 20
      xy_color: [0.526, 0.411]
    light.hue_outdoor_pedestal_2:
      state: off
    light.hue_outdoor_pedestal_3:
      state: on
      brightness: 20
      xy_color: [0.526, 0.411]
    light.hue_outdoor_pedestal_4:
      state: on
      brightness: 20
      xy_color: [0.526, 0.411]
    light.hue_outdoor_spot_1:
      state: off
    light.hue_outdoor_spot_2:
      state: off
    light.hue_outdoor_spot_3:
      state: off
    light.hue_outdoor_spot_4:
      state: off
    light.hue_outdoor_spot_5:
      state: off
- name: Back Garden Bright
  entities:
    light.terrace_light:
      state: on
      brightness: 224
      xy_color: [0.26, 0.1]
    light.hue_outdoor_pedestal_1:
      state: on
      brightness: 255
      xy_color: [0.435, 0.201]
    light.hue_outdoor_pedestal_2:
      state: on
      brightness: 255
      xy_color: [0.499, 0.415]
    light.hue_outdoor_pedestal_3:
      state: on
      brightness: 255
      xy_color: [0.435, 0.201]
    light.hue_outdoor_pedestal_4:
      state: on
      brightness: 255
      xy_color: [0.435, 0.201]
    light.hue_outdoor_spot_1:
      state: on
      brightness: 224
      xy_color: [0.179, 0.413]
    light.hue_outdoor_spot_2:
      state: on
      brightness: 255
      xy_color: [0.157, 0.099]
    light.hue_outdoor_spot_3:
      state: on
      brightness: 224
      xy_color: [0.158, 0.19]
    light.hue_outdoor_spot_4:
      state: on
      brightness: 224
      xy_color: [0.521, 0.436]
    light.hue_outdoor_spot_5:
      state: on
      brightness: 224
      xy_color: [0.479, 0.328]
- name: Back Garden Colour Loop
  entities:
    light.terrace_light:
      state: on
      brightness: 224
      effect: colorloop
    light.hue_outdoor_pedestal_1:
      state: on
      brightness: 255
      effect: colorloop
    light.hue_outdoor_pedestal_2:
      state: on
      brightness: 255
      effect: colorloop
    light.hue_outdoor_pedestal_3:
      state: on
      brightness: 255
      effect: colorloop
    light.hue_outdoor_pedestal_4:
      state: on
      brightness: 255
      effect: colorloop
    light.hue_outdoor_spot_1:
      state: on
      brightness: 224
      effect: colorloop
    light.hue_outdoor_spot_2:
      state: on
      brightness: 255
      effect: colorloop
    light.hue_outdoor_spot_3:
      state: on
      brightness: 224
      effect: colorloop
    light.hue_outdoor_spot_4:
      state: on
      brightness: 224
      effect: colorloop
    light.hue_outdoor_spot_5:
      state: on
      brightness: 224
      effect: colorloop
- name: Upstairs Hallway Morning
  entities:
    light.upstairs_spot_1:
      state: on
      brightness: 29
      color_temp: 379
    light.upstairs_spot_2:
      state: on
      brightness: 29
      color_temp: 379
    light.upstairs_spot_3:
      state: on
      brightness: 29
      color_temp: 379
- name: Upstairs Hallway Daytime
  entities:
    light.upstairs_spot_1:
      state: on
      brightness: 63
      color_temp: 309
    light.upstairs_spot_2:
      state: on
      brightness: 76
      color_temp: 239
    light.upstairs_spot_3:
      state: on
      brightness: 109
      color_temp: 156
- name: Upstairs Hallway Evening
  entities:
    light.upstairs_spot_1:
      state: on
      brightness: 55
      color_temp: 454
    light.upstairs_spot_2:
      state: on
      brightness: 55
      color_temp: 393
    light.upstairs_spot_3:
      state: on
      brightness: 55
      color_temp: 294
- name: Upstairs Hallway Night
  entities:
    light.upstairs_spot_1:
      state: on
      brightness: 21
      color_temp: 454
    light.upstairs_spot_2:
      state: off
    light.upstairs_spot_3:
      state: on
      brightness: 17
      color_temp: 454
- name: Upstairs Hallway Off
  entities:
    light.upstairs_spot_1:
      state: off
    light.upstairs_spot_2:
      state: off
    light.upstairs_spot_3:
      state: off
- name: Upstairs Cupboard Open
  entities:
    light.upstairs_spot_2:
      state: on
      color_temp: 153
      brightness: 254
- name: Living Room Off
  entities:
    light.mushroom_lamp: off
    light.copper_lamp: off
    switch.living_room_main: off
- name: Living Room Bright
  entities:
    light.mushroom_lamp:
      state: on
      brightness: 255
      color_temp: 156
    light.copper_lamp:
      state: on
      brightness: 255
      color_temp: 156
    switch.living_room_main: on
- name: Living Room Morning
  entities:
    light.mushroom_lamp:
      state: on
      brightness: 255
      color_temp: 497
    light.copper_lamp:
      state: on
      brightness: 255
      color_temp: 497
    switch.living_room_main: off
- name: Living Room Dull Outside
  entities:
    light.mushroom_lamp:
      state: on
      brightness: 104
      xy_color: [ 0.257, 0.218 ]
    light.copper_lamp:
      state: on
      brightness: 62
      xy_color: [ 0.491, 0.415 ]
    switch.living_room_main: off
- name: Living Room Evening
  entities:
    light.mushroom_lamp:
      state: on
      brightness: 141
      xy_color: [ 0.264, 0.119 ]
    light.copper_lamp:
      state: on
      brightness: 141
      xy_color: [ 0.159, 0.241 ]
    switch.living_room_main: off
- name: Downstairs Hallway Off
  entities:
    light.play_left: off
    light.play_right: off
    light.downstairs_hallway_1: off
    light.downstairs_hallway_2: off
    light.downstairs_hallway_3: off
    light.downstairs_hallway_4: off
    light.downstairs_hallway_5: off
    light.downstairs_hallway_6: off
- name: Downstairs Hallway Colourful Evening
  entities:
    light.play_left:
      state: on
      brightness: 90
      xy_color:
        - 0.473
        - 0.331
    light.play_right:
      state: on
      brightness: 87
      xy_color:
        - 0.473
        - 0.331
    light.downstairs_hallway_1:
      state: on
      brightness: 128
      xy_color:
        - 0.165
        - 0.479
    light.downstairs_hallway_2:
      state: on
      brightness: 111
      xy_color:
        - 0.434
        - 0.185
    light.downstairs_hallway_3:
      state: on
      brightness: 90
      xy_color:
        - 0.205
        - 0.074
    light.downstairs_hallway_4:
      state: on
      brightness: 90
      xy_color:
        - 0.158
        - 0.198
    light.downstairs_hallway_5:
      state: on
      brightness: 87
      xy_color:
        - 0.509
        - 0.36
    light.downstairs_hallway_6:
      state: on
      brightness: 109
      xy_color:
        - 0.579
        - 0.256
- name: Downstairs Hallway Colourful Evening Away
  entities:
    light.play_left:
      state: on
      brightness: 90
      xy_color:
        - 0.473
        - 0.331
    light.play_right: off
    light.downstairs_hallway_1:
      state: on
      brightness: 128
      xy_color:
        - 0.165
        - 0.479
    light.downstairs_hallway_2:
      state: on
      brightness: 111
      xy_color:
        - 0.434
        - 0.185
    light.downstairs_hallway_3:
      state: on
      brightness: 90
      xy_color:
        - 0.205
        - 0.074
    light.downstairs_hallway_4: off
    light.downstairs_hallway_5: off
    light.downstairs_hallway_6: off
- name: Downstairs Hallway Daytime Presence
  entities:
    light.play_left:
      state: on
      brightness: 45
      xy_color:
        - 0.173
        - 0.698
    light.play_right:
      state: on
      brightness: 59
      xy_color:
        - 0.192
        - 0.306
    light.downstairs_hallway_1: off
    light.downstairs_hallway_2: off
    light.downstairs_hallway_3: off
    light.downstairs_hallway_4: off
    light.downstairs_hallway_5:
      state: on
      brightness: 28
      xy_color:
        - 0.314
        - 0.331
    light.downstairs_hallway_6:
      state: on
      brightness: 54
      xy_color:
        - 0.314
        - 0.331
- name: Downstairs Hallway Early Night
  entities:
    light.play_left: off
    light.play_right: off
    light.downstairs_hallway_1: off
    light.downstairs_hallway_2: off
    light.downstairs_hallway_3:
      state: on
      brightness: 29
      xy_color:
        - 0.169
        - 0.371
    light.downstairs_hallway_4:
      state: on
      brightness: 29
      xy_color:
        - 0.3
        - 0.12
    light.downstairs_hallway_5: off
    light.downstairs_hallway_6:
      state: on
      brightness: 29
      xy_color:
        - 0.464
        - 0.277
- name: Downstairs Hallway Late Evening
  entities:
    light.play_left:
      state: on
      brightness: 31
      xy_color:
        - 0.473
        - 0.331
    light.play_right:
      state: on
      brightness: 30
      xy_color:
        - 0.473
        - 0.331
    light.downstairs_hallway_1:
      state: on
      brightness: 44
      xy_color:
        - 0.165
        - 0.479
    light.downstairs_hallway_2:
      state: on
      brightness: 39
      xy_color:
        - 0.434
        - 0.185
    light.downstairs_hallway_3:
      state: on
      brightness: 32
      xy_color:
        - 0.205
        - 0.074
    light.downstairs_hallway_4:
      state: on
      brightness: 32
      xy_color:
        - 0.158
        - 0.198
    light.downstairs_hallway_5:
      state: on
      brightness: 31
      xy_color:
        - 0.509
        - 0.36
    light.downstairs_hallway_6:
      state: on
      brightness: 38
      xy_color:
        - 0.579
        - 0.256
- name: Downstairs Hallway Late Evening Away
  entities:
    light.play_left:
      state: on
      brightness: 31
      xy_color:
        - 0.473
        - 0.331
    light.play_right: off
    light.downstairs_hallway_1:
      state: on
      brightness: 44
      xy_color:
        - 0.165
        - 0.479
    light.downstairs_hallway_2:
      state: on
      brightness: 39
      xy_color:
        - 0.434
        - 0.185
    light.downstairs_hallway_3:
      state: on
      brightness: 32
      xy_color:
        - 0.205
        - 0.074
    light.downstairs_hallway_4: off
    light.downstairs_hallway_5: off
    light.downstairs_hallway_6: off
- name: Downstairs Hallway Morning
  entities:
    light.play_left:
      state: on
      brightness: 113
      xy_color:
        - 0.171
        - 0.059
    light.play_right:
      state: on
      brightness: 117
      xy_color:
        - 0.159
        - 0.235
    light.downstairs_hallway_1:
      state: on
      brightness: 247
      xy_color:
        - 0.173
        - 0.175
    light.downstairs_hallway_2:
      state: on
      brightness: 148
      xy_color:
        - 0.314
        - 0.331
    light.downstairs_hallway_3:
      state: on
      brightness: 173
      xy_color:
        - 0.526
        - 0.411
    light.downstairs_hallway_4:
      state: on
      brightness: 255
      xy_color:
        - 0.583
        - 0.389
    light.downstairs_hallway_5:
      state: on
      brightness: 69
      xy_color:
        - 0.464
        - 0.411
    light.downstairs_hallway_6:
      state: on
      brightness: 183
      xy_color:
        - 0.526
        - 0.411
- name: Downstairs Hallway Morning Away
  entities:
    light.play_left: off
    light.play_right: off
    light.downstairs_hallway_1:
      state: on
      brightness: 247
      xy_color:
        - 0.173
        - 0.175
    light.downstairs_hallway_2:
      state: on
      brightness: 148
      xy_color:
        - 0.314
        - 0.331
    light.downstairs_hallway_3:
      state: on
      brightness: 173
      xy_color:
        - 0.526
        - 0.411
    light.downstairs_hallway_4: off
    light.downstairs_hallway_5: off
    light.downstairs_hallway_6: off
