---
- name: Create Temporary skyq directory
  delegate_to: 127.0.0.1
  tempfile:
    state: directory
    suffix: skyq
  register: tempdir

- name: Pull SkyQ MediaPlayer Custom Component
  delegate_to: 127.0.0.1
  git:
    repo: 'https://github.com/4n0nD3v3l0p3r/Home_Assistant_SkyQ_MediaPlayer'
    dest: "{{ tempdir.path }}"

- name: Remove .git folder
  file:
    state: absent
    path: "{{ tempdir.path }}/.git"

- name: Create skyq_mediaplayer custom component directory
  delegate_to: 127.0.0.1
  file:
    path: ./roles/home-assistant/files/custom_components/skyq
    state: directory

- name: Copy latest custom component to home-assistant role
  delegate_to: 127.0.0.1
  copy:
    src: "{{ tempdir.path }}/"
    dest: ./roles/home-assistant/files/custom_components/skyq

- name: Cleanup
  delegate_to: 127.0.0.1
  file:
    path: "{{ tempdir.path }}"
    state: absent
  when: tempdir.path is defined
