---
- name: Create data directory
  become: yes
  file:
    path: /opt/docker/data/chronograf
    state: directory
    owner: "104"

- name: Tear down existing service
  docker_compose:
    project_name: chronograf
    state: absent
    definition:
        version: "3"
        services:
            chronograf:
                image: ""

- name: Start service
  docker_compose:
    project_name: chronograf
    remove_orphans: yes
    state: present
    definition:
      version: '3'
      services:
        chronograf:
          container_name: chronograf
          image: chronograf:1.8-alpine
          restart: unless-stopped
          environment:
            TZ: Europe/London
          ports:
              - 8888:8888
          volumes:
            - /opt/docker/data/chronograf:/var/lib/chronograf
