- alias: Dark Outside
  hide_entity: true
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.front_garden_motion_light_level
    below: 600
  condition:
    condition: time
    before: "21:00:00"
    after: "08:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Garden
        scene_name: Dimmed
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Colourful Evening
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Evening
    - service: hue.hue_activate_scene
      data:
        group_name: "Living room"
        scene_name: "Living Room Evening"

- alias: Bright Outside
  hide_entity: true
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.front_garden_motion_light_level
    above: 600
    below: 3000
  condition:
    condition: time
    before: "21:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Daytime Presence
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Daytime Presence
    - service: light.turn_off
      data:
        entity_id:
          - group.garden
          - group.living_room
          - group.ethans_room
          - group.marcuss_room
          - group.bedroom
          - group.guest_room
          - group.snug

- alias: Very Bright Outside
  hide_entity: true
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.front_garden_motion_light_level
    above: 3000
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Bright Outside
    - service: light.turn_off
      data:
        entity_id:
          - group.downstairs_hallway
          - group.garden
          - group.living_room
          - group.ethans_room
          - group.marcuss_room
          - group.bedroom
          - group.guest_room
          - group.snug

- alias: Wakeup
  hide_entity: true
  initial_state: true
  trigger:
    platform: time
    at: "06:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Morning Variation
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Morning
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Morning
    - service: light.turn_off
      data:
        entity_id:
          - group.ethans_room
          - group.marcuss_room
    - service: media_player.media_pause
      data:
        entity_id:
          - media_player.ethan_s_room
          - media_player.marcus_room

- alias: Kids Bedtime
  hide_entity: true
  initial_state: true
  trigger:
    platform: time
    at: "21:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Upstairs Hallway
        scene_name: Night

- alias: Late Night
  hide_entity: true
  initial_state: true
  trigger:
    platform: time
    at: "22:30:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Late Night

- alias: Lights Out
  hide_entity: true
  initial_state: true
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Downstairs Hallway
        scene_name: Night
    - service: light.turn_off
      data:
        entity_id:
          - light.living_room
          - light.bedroom

- alias: Start Kitchen Light Timer
  hide_entity: true
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_motion
      from: "off"
      to: "on"
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light
    - service: timer.start
      entity_id: timer.kitchen_light

- alias: Kitchen Worktop Lights On
  hide_entity: true
  initial_state: true
  trigger:
    - platform: state
      entity_id: timer.kitchen_light
      from: "idle"
      to: "active"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.worktop_lights

- alias: Kitchen Worktop Lights Off
  hide_entity: true
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_light
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.worktop_lights

- alias: Start Garden Light Timer
  hide_entity: true
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.front_garden_motion_motion
      from: "off"
      to: "on"
  condition:
    - condition: numeric_state
      entity_id: sensor.front_garden_motion_light_level
      below: 50
  action:
    - service: timer.cancel
      entity_id: timer.garden_light
    - service: timer.start
      entity_id: timer.garden_light

- alias: Brighten the Garden
  hide_entity: true
  initial_state: true
  condition:
    - condition: state
      entity_id: timer.garden_light
      state: "idle"
      for:
        seconds: 5
  trigger:
    - platform: state
      entity_id: timer.garden_light
      from: "idle"
      to: "active"
  action:
    - service: scene.create
      data:
        scene_id: garden_before
        snapshot_entities:
          - light.garden
    - service: hue.hue_activate_scene
      data:
        group_name: Garden
        scene_name: Bright

- alias: Restore garden lights
  hide_entity: true
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.garden_light
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.garden_before

- alias: Bathroom Light Left On
  hide_entity: true
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.bathroom_2
      to: "On"
      for:
        minutes: 30
  action:
    - service: notify.mobile_app_barrys_iphone
      data:
        message: 'Bathroom Light Left On'

- alias: Ensuite Light Left On
  hide_entity: true
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.ensuite_2
      to: "On"
      for:
        minutes: 30
  action:
    - service: notify.mobile_app_barrys_iphone
      data:
        message: 'Ensuite Light Left On'

- alias: Downstairs Toilet Light Left On
  hide_entity: true
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.downstairs_toilet_2
      to: "On"
      for:
        minutes: 30
  action:
    - service: notify.mobile_app_barrys_iphone
      data:
        message: 'Downstairs Toilet Light Left On'

- alias: Turn Power Amp On
  hide_entity:  true
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.hifi
      from: "off"
      for:
        seconds: 2
  action:
    - service: switch.turn_on
      entity_id: switch.power_amplifier

- alias: Turn Power Amp Off
  hide_entity:  true
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.hifi
      to: "off"
      for:
        seconds: 30
  action:
    - service: switch.turn_off
      entity_id: switch.power_amplifier