# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  base_url: {{ homeassistant.base_url }}

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: Home
  latitude: "{{ homeassistant.latitude }}"
  longitude: "{{ homeassistant.longitude }}"
  elevation: "{{ homeassistant.elevation }}"
  unit_system: metric
  time_zone: Europe/London
  customize:
    media_player.epson_projector:
      friendly_name: Projector
      icon: mdi-projector
    media_player.power_amplifier:
      icon: mdi-speaker

cloud:
  alexa:
    filter:
      include_entities:
        - light.kitchen
        - light.worktop_lights
        - light.dining_table
        - light.outside_light
        - light.bathroom
        - light.bedroom
        - light.downstairs_hallway
        - light.downstairs_toilet
        - light.ensuite
        - light.guest_room
        - light.ethans_room
        - light.living_room
        - light.marcuss_room
        - media_player.hifi
        - light.snug
        - light.upstairs_hallway
        - media_player.epson_projector

discovery:

hue:

media_player:
  - platform: openhome
  - platform: epson
    host: 192.168.1.157

rfxtrx:
  device: /dev/rfxtrx

light:
  platform: rfxtrx
  devices:
    "0710080041030000":
      name: Worktop Lights

switch:
  platform: rfxtrx
  devices:
    "0710080041040000":
      name: Power Amplifier

sensor:
  - platform: rfxtrx
    automatic_add: true
    devices:
      0a520a02930200b8120279:
        name: Guest Room
        data_type:
        - Humidity
        - Temperature
      0a520a01880200b4340179:
        name: "Ethan's Room"
        data_type:
        - Humidity
        - Temperature
      0a520a03810300b9310179:
        name: "Marcus' Room"
        data_type:
        - Humidity
        - Temperature
      0a520a04a80300b5320179:
        name: Bedroom
        data_type:
        - Humidity
        - Temperature

weather:
  - platform: darksky
    api_key: {{ darksky.api_key }}

input_boolean:
  garden_scene_saved:
    name: Garden Scene Saved
    initial: off

timer:
  kitchen_light:
    duration: "00:10:00"

notify:
  - platform: alexa_media
    name: alexa_media

alexa_media:
  accounts:
    - email: {{ alexa.email }}
      password: {{ alexa.password }}
      url: {{ alexa.region }}
      include_devices:
        - 4k Fire TV
        - Fire TV Stick
        - Bedroom
        - "Ethan's Room"
        - "Marcus' Room"
        - Snug Echo
        - Kiko Echo
        - Kitchen Show
        - Downstairs
        - Kids Rooms

homeconnect:
  client_id: {{ homeconnect.client_id }}
  client_secret: {{ homeconnect.client_secret }}

ring:
  username: {{ ring.username }}
  password: {{ ring.password }}