config:
frontend:
map:
mobile_app:
person:
ssdp:
sun:
system_health:
updater:
zeroconf:
zone:
history:
logbook:

recorder:
  auto_purge: true
  purge_keep_days: 3
  exclude:
    domains:
      - updater
    entities:
      - sensor.last_boot
      - sensor.time

logger:
  default: warning

influxdb:
  exclude:
    domains:
      - updater
    entities:
      - sensor.last_boot
      - sensor.time

http:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: Home
  latitude: "{{ homeassistant.latitude }}"
  longitude: "{{ homeassistant.longitude }}"
  elevation: "{{ homeassistant.elevation }}"
  unit_system: metric
  time_zone: Europe/London
  customize:
    media_player.epson_projector:
      friendly_name: Projector
      icon: mdi:projector
    light.dining_table:
      friendly_name: Dining Table
      icon: mdi:vanity-light
    alarm_control_panel.unnamed_device:
      friendly_name: Alarm
    light.snug_main:
      friendly_name: Snug Main
      icon: mdi:ceiling-light
    light.bedroom_main:
      friendly_name: Bedroom Light
      icon: mdi:ceiling-light
    light.bookcase:
      friendly_name: Bookcase
      icon: mdi:book-open-variant
    light.turntable_light:
      friendly_name: Turntable Light
      icon: mdi:record-player
    light.lava_lamp:
      friendly_name: Lava Lamp
      icon: mdi:lava-lamp
    switch.frog_filter:
      friendly_name: Frog Filter
      icon: mdi:air-filter
    light.tripod_lamp:
      icon: mdi:floor-lamp-variant
    light.steampunk_lamp:
      icon: mdi:desk-lamp
    switch.diffuser:
      friendly_name: Diffuser
      icon: mdi:air-purifier
    light.downstairs_toilet_main:
      friendly_name: Downstairs Toilet
    light.bathroom:
      friendly_name: Bathroom
    media_player.living_room_tv:
      friendly_name: Television
      icon: mdi:television
    input_boolean.bfl:
      friendly_name: Big Light
      icon: mdi:ceiling-light
    binary_sensor.upstairs_hallway_motion:
      friendly_name: Upstairs Hallway Motion
    sensor.upstairs_hallway_motion:
      friendly_name: Upstairs Hallway Light Level
    sensor.kitchen_motion:
      friendly_name: Kitchen Temperature
    sensor.kitchen_motion_2:
      friendly_name: Kitchen Light Level
    binary_sensor.kitchen_motion:
      friendly_name: Kitchen Motion
    binary_sensor.front_garden_motion:
      friendly_name: Front Garden Motion
    sensor.front_garden_temperature:
      friendly_name: Front Garden Temperature
    sensor.front_garden_temperature_2:
      friendly_name: Front Garden Light Level
    binary_sensor.back_garden_motion:
      friendly_name: Back Garden Motion
    sensor.back_garden_motion:
      friendly_name: Back Garden Temperature
    sensor.back_garden_motion_2:
      friendly_name: Back Garden Light Level      
    sensor.bathroom_environment:
      friendly_name: Bathroom Temperature
    sensor.bathroom_environment_2:
      friendly_name: Bathroom Humidity
    sensor.bathroom_environment_3:
      friendly_name: Bathroom Pressure
    sensor.studio_environment:
      friendly_name: Studio Temperature
    sensor.studio_environment_2:
      friendly_name: Studio Humidity
    sensor.studio_environment_3:
      friendly_name: Studio Pressure
    sensor.food_store_environment:
      friendly_name: Food Store Temperature
    sensor.food_store_environment_2:
      friendly_name: Food Store Humidity
    sensor.food_store_environment_3:
      friendly_name: Food Store Pressure
    binary_sensor.downstairs_hallway_motion:
      friendly_name: Stairs Motion
    sensor.downstairs_hallway_motion:
      friendly_name: Stairs Light Level
    switch.socket:
      friendly_name: Christmas Tree
        
cloud:
  alexa:
    filter:
      include_entities:
        - vacuum.kryten
        - switch.socket
        - light.kitchen
        - light.worktop_lights
        - light.dining_table
        - light.terrace
        - light.bedroom
        - light.downstairs_hallway
        - light.guest_room
        - light.ethans_room
        - light.living_room
        - light.marcuss_room
        - light.snug
        - light.upstairs_hallway
        - media_player.epson_projector
        - switch.lava_lamp
        - light.bookcase
        - switch.frog_filter
        - media_player.living_room_tv
        - input_boolean.bfl

light:
  - platform: switch
    name: Lava Lamp
    entity_id: switch.lava_lamp
  - platform: switch
    name: Bedroom Main
    entity_id: switch.bedroom_main
  - platform: switch
    name: Turntable Light
    entity_id: switch.turntable_light

sensor:
  - platform: uptime
    unit_of_measurement: minutes
  - platform: min_max
    name: Outside Light Level
    entity_ids:
    - sensor.front_garden_motion_2
    - sensor.back_garden_motion_2
    type: min
  - platform: min_max
    name: Outside Temperature
    entity_ids:
    - sensor.front_garden_motion
    - sensor.back_garden_motion
    type: min
  - platform: time_date
    display_options:
      - 'time'
  - platform: template
    sensors:
      house_mode:
        unique_id: house_mode
        friendly_name: 'House Mode'
        value_template: >-
{% raw %}
          {% if states("sensor.uptime") | float > 5 %}
          {% if now().hour | int >= 22 %}
          {% set time_slot = "early_night" %}
          {% elif now().hour | int >= 20 %}
          {% set time_slot = "late_evening" %}
          {% elif now().hour | int >= 19 %}
          {% set time_slot = "evening" %}
          {% elif now().hour | int >= 8 %}
          {% set time_slot = "daytime" %}
          {% elif now().hour | int >= 6 %}
          {% set time_slot = "morning" %}
          {% elif now().hour | int >= 1 %}
          {% set time_slot = "night" %}
          {% elif now().hour | int >= 0 %}
          {% set time_slot = "late_night" %}
          {% endif %}
          {% if states("sensor.outside_light_level") | float < 50 %}
          {% set light_slot = "dark" %}
          {% elif states("sensor.outside_light_level") | float  < 600 %}
          {% set light_slot = "dim" %}
          {% elif states("sensor.outside_light_level") | float  < 3000 %}
          {% set light_slot = "bright" %}
          {% else %}
          {% set light_slot = "very_bright" %}
          {% endif %}
          {% if is_state("alarm_control_panel.unnamed_device", "armed_home") or is_state("alarm_control_panel.unnamed_device", "armed_away")%}
          {% set presence = "away" %}
          {% else %}
          {% set presence = "home" %}
          {% endif %}
          {{ time_slot }}_{{ light_slot }}_{{ presence }}
          {% else %}
          homeassistant_starting
          {% endif %}
{% endraw %}

input_boolean:
  terrace_occupancy:
    name: Motion detected in the garden
    initial: off
  bfl:
    name: Living Room should be bright
    initial: off

input_text:
  bedroom_mode:
    name: Bedroom Scene Mode
    initial: scene_off
  kitchen_scene:
    name: Kitchen Scene
    initial: kitchen_morning
  upstairs_hallway_scene:
    name: Upstairs Hallway Scene
    initial: upstairs_hallway_night
  front_garden_scene:
    name: Front Garden Scene
    initial: front_garden_off
  back_garden_scene:
    name: Back Garden Scene
    initial: back_garden_off
  living_room_scene:
    name: Living Room Scene
    initial: living_room_off
  staircase_scene:
    name: Staircase Scene
    initial: stairs_decorative_pastel
  downstairs_hallway_scene:
    name: Downstairs Hallway Scene
    initial: downstairs_hallway_off
  snug_scene:
    name: Snug Scene
    initial: snug_off
  downstairs_toilet_scene:
    name: Downstairs Toilet Scene
    initial: downstairs_toilet_bright

wake_on_lan:

webostv:
  host: 192.168.1.36
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "44:cb:8b:f8:a7:f2"

hive:
  username: {{ hive.username }}
  password: {{ hive.password }}

climate:
  - platform: generic_thermostat
    name: Studio
    heater: switch.studio_heater
    target_sensor: sensor.studio_environment
    away_temp: 7
    target_temp: 20
    precision: 0.1
    cold_tolerance: 1
    hot_tolerance: 0
    min_cycle_duration:
      minutes: 1

home_connect:
  client_id: {{ homeconnect.client_id }}
  client_secret: {{ homeconnect.client_secret }}

securitas_direct:
  username: {{ verisure.username }}
  password: {{ verisure.password }}
  installation: {{ verisure.installation }}
  code: {{ alarm.code }}
  country: GB