config:
frontend:
map:
mobile_app:
person:
ssdp:
sun:
system_health:
updater:
zeroconf:
zone:
history:
logbook:

recorder:
  auto_purge: true
  purge_keep_days: 3
  exclude:
    domains:
      - automation
      - updater
    entities:
      - sensor.last_boot
      - sensor.time

logger:
  default: warning

influxdb:
  exclude:
    domains:
      - updater
    entities:
      - sensor.last_boot
      - sensor.time

http:

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: Home
  latitude: "{{ homeassistant.latitude }}"
  longitude: "{{ homeassistant.longitude }}"
  elevation: "{{ homeassistant.elevation }}"
  unit_system: metric
  time_zone: Europe/London
  customize:
    media_player.epson_projector:
      friendly_name: Projector
      icon: mdi:projector
    media_player.hifi_roon:
      friendly_name: HiFi
    media_player.living_room_roon:
      friendly_name: Living Room Music
    light.dining_table:
      friendly_name: Dining Table
      icon: mdi:vanity-light
    device_tracker.74_9e_af_4f_70_94:
      friendly_name: Barry's iPhone
    device_tracker.80_82_23_6a_ef_fc:
      friendly_name: Louise's iPhone
    alarm_control_panel.securitas_260178:
      friendly_name: Alarm
    light.snug_main:
      friendly_name: Snug Main
      icon: mdi:ceiling-light
    switch.living_room_main:
      friendly_name: Big Light
      icon: mdi:ceiling-light
    light.snug_bookcase:
      friendly_name: Reading Light
      icon: mdi:book-open-variant
    switch.turntable:
      friendly_name: Turntable Light
      icon: mdi:record-player
    switch.lava_lamp:
      friendly_name: Lava Lamp
      icon: mdi:lava-lamp
    switch.frog_filter:
      friendly_name: Frog Filter
      icon: mdi:air-filter
    light.tripod_lamp:
      icon: mdi:floor-lamp-variant
    light.steampunk_lamp:
      icon: mdi:desk-lamp
    climate.bedroom_heating:
      friendly_name: Upstairs Heating
    climate.living_room_heating:
      friendly_name: Downstairs Heating
    switch.partylite_diffuser:
      friendly_name: Diffuser
      icon: mdi:air-purifier
    sensor.upstairs_hallway_light_level:
      friendly_name: Upstairs Hallway Light Level
    sensor.kitchen_temperature:
      friendly_name: Kitchen Temperature
    sensor.kitchen_light_level:
      friendly_name: Kitchen Light Level
    binary_sensor.kitchen_occupancy:
      friendly_name: Kitchen Motion
    binary_sensor.front_garden_occupancy:
      friendly_name: Front Garden Motion
    sensor.front_garden_light_level:
      friendly_name: Front Garden Light Level
    sensor.front_garden_temperature:
      friendly_name: Front Garden Temperature
    sensor.back_garden_light_level:
      friendly_name: Back Garden Light Level
    binary_sensor.back_garden_occupancy:
      friendly_name: Back Garden Motion
    sensor.back_garden_temperature:
      friendly_name: Back Garden Temperature
    light.downstairs_toilet:
      friendly_name: Downstairs Toilet
    light.bathroom:
      friendly_name: Bathroom
    media_player.living_room_tv:
      friendly_name: Television
      icon: mdi:television
        
cloud:
  alexa:
    filter:
      include_entities:
        - light.kitchen
        - light.worktop_lights
        - light.dining_table
        - light.terrace
        - light.bedroom
        - light.downstairs_hallway
        - light.guest_room
        - light.ethans_room
        - light.living_room
        - light.marcuss_room
        - media_player.hifi_roon
        - media_player.living_room_roon
        - light.snug
        - light.upstairs_hallway
        - media_player.epson_projector
        - switch.living_room_main
        - switch.lava_lamp
        - light.snug_bookcase
        - switch.frog_filter
        - climate.bedroom_heating
        - climate.living_room_heating
        - media_player.living_room_tv

# discovery:

media_player:
#   - platform: openhome
  - platform: epson
    host: 192.168.1.50

zha:
  usb_path: /dev/conbee2
  database_path: /config/zigbee.db
  radio_type: deconz

zha_map:

binary_sensor:
  - platform: bayesian
    prior: 0.5
    probability_threshold: 0.7
    name: Possibly Present
    device_class: presence
    observations:
      - entity_id: alarm_control_panel.securitas_260178
        platform: state
        prob_given_true: 1
        to_state: 'armed_night'
      - entity_id: alarm_control_panel.securitas_260178
        platform: state
        prob_given_true: 0
        to_state: 'armed_home'
      - entity_id: alarm_control_panel.securitas_260178
        platform: state
        prob_given_true: 0
        to_state: 'armed_away'
      - platform: template
        value_template: >
          {% raw %} {{((as_timestamp(now()) - as_timestamp(states.binary_sensor.kitchen_occupancy.last_changed)) < 1800)}} {% endraw %}

        prob_given_true: 1
        prob_given_false: 0.5
      - entity_id: device_tracker.74_9e_af_4f_70_94
        platform: state
        prob_given_true: 0.95
        prob_given_false: 0.5
        to_state: 'home'
      - entity_id: device_tracker.80_82_23_6a_ef_fc
        platform: state
        prob_given_true: 0.95
        prob_given_false: 0.5
        to_state: 'home'
      - entity_id: device_tracker.barrys_iphone
        platform: state
        to_state: 'home'
        prob_given_true: 0.6
        prob_given_false: 0.5
      - entity_id: device_tracker.holly
        platform: state
        to_state: 'home'
        prob_given_true: 0.6
        prob_given_false: 0.5

sensor:
  - platform: min_max
    name: Outside Light Level
    entity_ids:
    - sensor.front_garden_light_level
    - sensor.back_garden_light_level
    type: min
  - platform: min_max
    name: Outside Temperature
    entity_ids:
    - sensor.front_garden_temperature
    - sensor.back_garden_temperature
    type: min
  - platform: time_date
    display_options:
      - 'time'
  - platform: template
    sensors:
      # living_room_temperature_hive:
      #   entity_id:
      #   - climate.living_room_heating
      #   friendly_name: 'Living Room Temperature'
      #   unit_of_measurement: °C
      #   value_template:  >
      #     {% raw %}{{ state_attr('climate.living_room_heating', 'current_temperature') }} {% endraw %}

      # bedroom_temperature_hive:
      #   entity_id:
      #   - climate.bedroom_heating
      #   friendly_name: 'Bedroom Temperature'
      #   unit_of_measurement: °C
      #   value_template: >
      #     {% raw %} {{ state_attr('climate.bedroom_heating', 'current_temperature') }} {% endraw %}

      # ethans_room_temperature_hive:
      #   entity_id:
      #   - climate.ethans_room
      #   friendly_name: 'Ethan's Room Temperature'
      #   unit_of_measurement: °C
      #   value_template: >
      #     {% raw %} {{ state_attr('climate.ethans_room', 'current_temperature') }} {% endraw %}

      # marcus_room_temperature_hive:
      #   entity_id:
      #   - climate.marcus_room
      #   friendly_name: 'Marcus' Room Temperature'
      #   unit_of_measurement: °C
      #   value_template: >
      #     {% raw %} {{ state_attr('climate.marcus_room', 'current_temperature') }} {% endraw %}

      # hobby_room_temperature_hive:
      #   entity_id:
      #   - climate.hobby_room
      #   friendly_name: 'Hobby Room Temperature'
      #   unit_of_measurement: °C
      #   value_template: >
      #     {% raw %} {{ state_attr('climate.hobby_room', 'current_temperature') }} {% endraw %}

      # kitchen_temperature_hive:
      #   entity_id:
      #   - climate.kitchen
      #   friendly_name: 'Kitchen Temperature'
      #   unit_of_measurement: °C
      #   value_template: >
      #     {% raw %} {{ state_attr('climate.hobby_room', 'current_temperature') }} {% endraw %}
    
      house_mode:
        entity_id:
        - sensor.outside_light_level
        - sensor.time
        - binary_sensor.possibly_present
        friendly_name: 'House Mode'
        value_template: >-
{% raw %}
          {% if now().hour | int >= 22 %}
          {% set time_slot = "early_night" %}
          {% elif now().hour | int >= 20 %}
          {% set time_slot = "late_evening" %}
          {% elif now().hour | int >= 19 %}
          {% set time_slot = "evening" %}
          {% elif now().hour | int >= 8 %}
          {% set time_slot = "daytime" %}
          {% elif now().hour | int >= 6 %}
          {% set time_slot = "morning" %}
          {% elif now().hour | int >= 1 %}
          {% set time_slot = "night" %}
          {% elif now().hour | int >= 0 %}
          {% set time_slot = "late_night" %}
          {% endif %}
          {% if states("sensor.outside_light_level") | float < 200 %}
          {% set light_slot = "dark" %}
          {% elif states("sensor.outside_light_level") | float  < 800 %}
          {% set light_slot = "dim" %}
          {% elif states("sensor.outside_light_level") | float  < 3000 %}
          {% set light_slot = "bright" %}
          {% else %}
          {% set light_slot = "very_bright" %}
          {% endif %}
          {% if is_state("binary_sensor.possibly_present", "on") %}
          {% set presence = "home" %}
          {% else %}
          {% set presence = "away" %}
          {% endif %}
          {{ time_slot }}_{{ light_slot }}_{{ presence }}
{% endraw %}

weather:
  - platform: darksky
    api_key: {{ darksky.api_key }}

input_boolean:
  terrace_occupancy:
    name: Motion detected in the garden
    initial: off

input_text:
  bedroom_mode:
    name: Bedroom Scene Mode
    initial: scene_off
  guest_room_mode:
    name: Guest Room Scene Mode
    initial: scene_off
  marcuss_room_mode:
    name: Marcus' Room Scene Mode
    initial: scene_off
  ethans_room_mode:
    name: Ethan's Room Scene Mode
    initial: scene_off
  kitchen_scene:
    name: Kitchen Scene
    initial: kitchen_morning
  upstairs_hallway_scene:
    name: Upstairs Hallway Scene
    initial: upstairs_hallway_night
  front_garden_scene:
    name: Front Garden Scene
    initial: front_garden_off
  back_garden_scene:
    name: Back Garden Scene
    initial: back_garden_off
  living_room_scene:
    name: Living Room Scene
    initial: living_room_off
  staircase_scene:
    name: Staircase Scene
    initial: stairs_decorative_pastel
  downstairs_hallway_scene:
    name: Downstairs Hallway Scene
    initial: downstairs_hallway_off
  snug_scene:
    name: Snug Scene
    initial: snug_off

# notify:
#   - platform: alexa_media
#     name: alexa_media

# alexa_media:
#   accounts:
#     - email: {{ alexa.email }}
#       password: {{ alexa.password }}
#       url: {{ alexa.region }}
#       include_devices:
#         - 4k Fire TV
#         - Fire TV Stick
#         - Bedroom
#         - "Ethan's Room"
#         - "Marcus' Room"
#         - Snug Echo
#         - Kiko Echo
#         - Kitchen Show
#         - Downstairs
#         - Kids Rooms

roon:

wake_on_lan:

webostv:
  host: 192.168.1.53
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "44:cb:8b:f8:a7:f2"

hive:
  username: {{ hive.username }}
  password: {{ hive.password }}
  
# home_connect:
#   client_id: {{ homeconnect.client_id }}
#   client_secret: {{ homeconnect.client_secret }}

securitas_direct:
  username: {{ verisure.username }}
  password: {{ verisure.password }}
  code: {{ alarm.code }}
  country: GB

opnsense:
  url: {{ opnsense.url }}
  api_secret: {{ opnsense.api_secret }}
  api_key: {{ opnsense.api_key }}
  tracker_interfaces:
    - LAN
  verify_ssl: true