# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# logger:
#   default: warning
#   logs:
#     homeassistant.components.switch.rfxtrx: debug
#     homeassistant.components.binary_sensor.rfxtrx: debug
#     homeassistant.components.sensor.rfxtrx: debug
#     homeassistant.components.rfxtrx: debug

http:

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: Home
  latitude: "{{ homeassistant.latitude }}"
  longitude: "{{ homeassistant.longitude }}"
  elevation: "{{ homeassistant.elevation }}"
  unit_system: metric
  time_zone: Europe/London
  customize:
    media_player.epson_projector:
      friendly_name: Projector
      icon: mdi-projector
    media_player.power_amplifier:
      icon: mdi-speaker
    device_tracker.74_9e_af_4f_70_94:
      friendly_name: Barry's iPhone
    device_tracker.80_82_23_6a_ef_fc:
      friendly_name: Louise's iPhone
    alarm_control_panel.securitas_260178:
      friendly_name: Alarm

cloud:
  alexa:
    filter:
      include_entities:
        - light.kitchen
        - light.worktop_lights
        - light.dining_table
        - light.outside_light
        - light.bedroom
        - light.downstairs_hallway
        - light.guest_room
        - light.ethans_room
        - light.living_room
        - light.marcuss_room
        - media_player.hifi
        - light.snug
        - light.upstairs_hallway
        - media_player.epson_projector

discovery:

hue:

media_player:
  - platform: openhome
  - platform: epson
    host: 192.168.1.50
  - platform:  skyq
    name: SkyQ Living Room
    host: 192.168.1.58

rfxtrx:
  device: /dev/rfxtrx

light:
  platform: rfxtrx
  devices:
    "0710080041030000":
      name: Worktop Lights

switch:
  platform: rfxtrx
  devices:
    "0710080041040000":
      name: Power Amplifier

binary_sensor:
  - platform: rfxtrx
    automatic_add: true
    devices:
      "0a140006f4dcf40a000060":
        name: Upstairs Hall Cupboard Door
        device_class: opening
  - platform: bayesian
    prior: 0.5
    probability_threshold: 0.75
    name: Possibly Present
    device_class: presence
    observations:
      - entity_id: alarm_control_panel.securitas_260178
        platform: state
        prob_given_true: 1
        to_state: 'armed_night'
      - entity_id: alarm_control_panel.securitas_260178
        platform: state
        prob_given_true: 0
        to_state: 'armed_home'
      - entity_id: alarm_control_panel.securitas_260178
        platform: state
        prob_given_true: 0
        to_state: 'armed_away'
      - platform: template
        value_template: >
          {% raw %} {{((as_timestamp(now()) - as_timestamp(states.binary_sensor.kitchen_motion_motion.last_changed)) < 1800)}} {% endraw %}

        prob_given_true: 1
        prob_given_false: 0.5
      - entity_id: device_tracker.74_9e_af_4f_70_94
        platform: state
        prob_given_true: 0.95
        prob_given_false: 0.5
        to_state: 'home'
      - entity_id: device_tracker.80_82_23_6a_ef_fc
        platform: state
        prob_given_true: 0.95
        prob_given_false: 0.5
        to_state: 'home'
      - entity_id: device_tracker.barrys_iphone
        platform: state
        to_state: 'home'
        prob_given_true: 0.6
        prob_given_false: 0.5
      - entity_id: device_tracker.holly
        platform: state
        to_state: 'home'
        prob_given_true: 0.6
        prob_given_false: 0.5

sensor:
  - platform: rfxtrx
    automatic_add: true
    devices:
      0a520a02930200b8120279:
        name: Guest Room
        data_type:
          - Humidity
          - Temperature
      0a520a01880200b4340179:
        name: "Ethan's Room"
        data_type:
          - Humidity
          - Temperature
      0a520a03810300b9310179:
        name: "Marcus' Room"
        data_type:
          - Humidity
          - Temperature
      0a520a04a80300b5320179:
        name: Bedroom
        data_type:
          - Humidity
          - Temperature
  - platform: min_max
    name: Outside Light Level
    entity_ids:
    - sensor.front_garden_motion_light_level
    - sensor.terrace_light_level
    type: min
  - platform: min_max
    name: Outside Temperature
    entity_ids:
    - sensor.front_garden_motion_temperature
    - sensor.terrace_temperature
    type: min
  - platform: time_date
    display_options:
      - 'time'
  - platform: template
    sensors:
      house_mode:
        entity_id:
        - sensor.outside_light_level
        - sensor.time
        friendly_name: 'House Mode'
        value_template: >-
{% raw %}
          {% if now().hour | int >= 22 %}
          {% set time_slot = "early_night" %}
          {% elif now().hour | int >= 21 %}
          {% set time_slot = "late_evening" %}
          {% elif now().hour | int >= 19 %}
          {% set time_slot = "evening" %}
          {% elif now().hour | int >= 8 %}
          {% set time_slot = "daytime" %}
          {% elif now().hour | int >= 6 %}
          {% set time_slot = "morning" %}
          {% elif now().hour | int >= 0 %}
          {% set time_slot = "night" %}
          {% endif %}
          {% if states("sensor.outside_light_level") | float < 200 %}
          {% set light_slot = "dark" %}
          {% elif states("sensor.outside_light_level") | float  < 800 %}
          {% set light_slot = "dim" %}
          {% elif states("sensor.outside_light_level") | float  < 3000 %}
          {% set light_slot = "bright" %}
          {% else %}
          {% set light_slot = "very_bright" %}
          {% endif %}
          {% if is_state("binary_sensor.possibly_present", "on") %}
          {% set presence = "home" %}
          {% else %}
          {% set presence = "away" %}
          {% endif %}
          {{ time_slot }}_{{ light_slot }}_{{ presence }}
{% endraw %}

weather:
  - platform: darksky
    api_key: {{ darksky.api_key }}

input_boolean:
  front_garden_scene_saved:
    name: Front Garden Scene Saved
    initial: off

timer:
  kitchen_light:
    duration: "00:10:00"

notify:
  - platform: alexa_media
    name: alexa_media

alexa_media:
  accounts:
    - email: {{ alexa.email }}
      password: {{ alexa.password }}
      url: {{ alexa.region }}
      include_devices:
        - 4k Fire TV
        - Fire TV Stick
        - Bedroom
        - "Ethan's Room"
        - "Marcus' Room"
        - Snug Echo
        - Kiko Echo
        - Kitchen Show
        - Downstairs
        - Kids Rooms

homeconnect:
  client_id: {{ homeconnect.client_id }}
  client_secret: {{ homeconnect.client_secret }}

ring:
  username: {{ ring.username }}
  password: {{ ring.password }}

securitas_direct:
  username: {{ verisure.username }}
  password: {{ verisure.password }}
  code: {{ alarm.code }}
  country: GB

opnsense:
  url: {{ opnsense.url }}
  api_secret: {{ opnsense.api_secret }}
  api_key: {{ opnsense.api_key }}
  tracker_interfaces:
    - LAN
  verify_ssl: true